apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-blis-workload-profile
spec:
  description: |
    Create a workload profile for BLIS.

  params:
    - name: harness
      type: string
    - name: profileTemplate
      type: string

    - name: model
      type: string
    - name: targetUrl
      type: string

    - name: overrides
      type: string

  results:
    - name: profile
      description: Workload profile configuration file

  steps:
    - name: document-params
      image: alpine:3.20
      script: |
        #!/bin/sh
        set -eu

        cat <<EOF > $(results.profile.path)
        target: "$(prams.targetUrl)"
        rate-type: concurrent
        rate: 2
        max-seconds: 30
        data: prompt_tokens=256,output_tokens=128
        EOF