apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-workload-guidellm
spec:
  description: |
    Run workload using guidellm.

  workspaces:
    - name: data

  params:
    - name: modelLabel
      type: string
    - name: results_dir
      type: string


  steps:
    - name: create-profile
      env:
        - name: MODEL_LABEL
          value: "$(params.modelLabel)"
      image: alpine/kubectl:1.34.1
      script: |
        #!/bin/sh
        set -eu

        # TBD - move out of this task and pass as parameter or via results
        podIP=$(kubectl get po -l llm-d.ai/model=${MODEL_LABEL},llm-d.ai/role=decode -o jsonpath='{.items[0].status.podIP}')
        targetUrl="http://${podIP}:8000"

        WORKLOAD_PROFILE="$(workspaces.data.path)/$(params.results_dir)/profile.yaml"

        mkdir -p "$(workspaces.data.path)/$(params.results_dir)"

        cat <<EOF > ${WORKLOAD_PROFILE}
        target: "${targetUrl}"
        rate-type: sweep
        max-requests: 50 
        rate: 12
        random-seed: 42
        data: 
          prompt_tokens: 3500
          prompt_tokens_stdev: 2500
          prompt_tokens_min: 2
          prompt_tokens_max: 7168
          output_tokens: 800
          output_tokens_stdev: 500 
          output_tokens_min: 1
          output_tokens_max: 1024
        EOF

    - name: log-profile
      image: alpine:3.20
      script: |
        #!/bin/sh
        set -eu

        WORKLOAD_PROFILE="$(workspaces.data.path)/$(params.results_dir)/profile.yaml"
        echo ">>> created profile:"
        cat "${WORKLOAD_PROFILE}"

    - name: run-workload
      image: python:3.12.9-slim-bookworm
      script: |
        #!/bin/sh
        set -eu

        ROOT_DIR="$(workspaces.data.path)/$(params.results_dir)"
        mkdir -p "$(workspaces.data.path)/$(params.results_dir)"
        
        WORKLOAD_PROFILE="${ROOT_DIR}/profile.yaml"
        RESULTS="${ROOT_DIR}/guidellm-results.json"
        echo "ROOT_DIR=${ROOT_DIR}"
        echo "WORKLOAD_PROFILE=${WORKLOAD_PROFILE}"
        echo "RESULTS=${RESULTS}"

        echo "🔄 Installing required tools"
        apt-get update
        apt-get install -y \
          git \
          && apt-get clean && rm -rf /var/cache/apt

        pip install git+https://github.com/vllm-project/guidellm.git


        # run guidellm
        guidellm benchmark \
          --scenario "${WORKLOAD_PROFILE}" \
          --output-path "${RESULTS}" \
          --disable-progress \
          --request-type text_completions \
          --request-formatter-kwargs '{"stream": false}'
          # --display-scheduler-stats


        export RC=$?

        # If benchmark harness returned with an error, exit here
        if [ $RC -ne 0 ]; then
          echo "❌ Harness returned with error $RC"
          exit $RC
        fi
        echo "✅ Harness completed successfully."
