apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: train-blis-from-guidellm
spec:
  description: |
    Delete model engines
  
  workspaces:
    - name: data
  
  steps:
    - name: placeholder
      image: alpine:3.20
      script: |
        #!/bin/sh
        set -eu
        echo "train-blis-from-guidellm called"
