apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: training-run
spec:
  taskRunTemplate:
    serviceAccountName: helm-installer
  workspaces:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-pvc
    - name: data
      persistentVolumeClaim:
        claimName: workspace-pvc
    - name: hf-credentials
      secret:
        secretName: hf-secret
        items:
          - key: HF_TOKEN
            path: HF_TOKEN
    - name: target-credentials
      secret:
        secretName: ibm-cos-secret
        items:
          - key: AWS_ACCESS_KEY_ID
            path: AWS_ACCESS_KEY_ID
          - key: AWS_SECRET_ACCESS_KEY
            path: AWS_SECRET_ACCESS_KEY
  pipelineRef:
    name: blis-training
  params:
    - { name: experimentId, value: "mk-1" }
    - { name: model, value: "Qwen/Qwen2.5-Math-1.5B" }
    - { name: namespace, value: kalantar }
