experiment:
  name: blis-training
  description: Training pipeline for BLIS scenario 5

# modelId: meta-llama/Llama-3.3-70B-Instruct

stack:
  treatments:
    tensorParallelism:
      - 1
      - 2
      - 4

  model:
    helmValues:
      fullnameOverride: meta-llama-llama-3-1-8b-instruct
      multinode: false
      modelArtifacts:
        uri: pvc://model-pvc/models/meta-llama/Llama-3.1-8B-Instruct
        size: 300Gi
        authSecretName: "hf-secret"
        name: meta-llama/Llama-3.1-8B-Instruct
        labels:
          llm-d.ai/inferenceServing: "true"
          llm-d.ai/model: meta-llama-llama-3-1-8b-instruct

      routing:
        servicePort: 8000
        proxy:
          enabled: false
      decode:
        create: true
        replicas: 1
        acceleratorTypes:
            labelKey: nvidia.com/gpu.product
            labelValues:
              - NVIDIA-H100-80GB-HBM3
        parallelism:
          data: 1
          tensor: 1
        podAnnotations:
            k8s.v1.cni.cncf.io/networks: multi-nic-compute
        containers:
        - name: "vllm"
          mountModelVolume: true
          image: "ghcr.io/llm-d/llm-d:v0.2.0"
          modelCommand: vllmServe
          args:
            - "--block-size"
            - "128"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
            - "--disable-log-requests"
            - "--disable-uvicorn-access-log"
            - "--max-model-len"
            - "16000"
          env:
            - name: UCX_TLS
              value: "rc,sm,cuda_ipc,cuda_copy,tcp"
            - name: UCX_SOCKADDR_TLS_PRIORITY
              value: "tcp"
            - name: UCX_NET_DEVICES
              value: mlx5_1:1
            - name: NCCL_IB_HCA
              value: mlx5_1
            - name: VLLM_NIXL_SIDE_CHANNEL_PORT
              value: "5557"
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_LOGGING_LEVEL
              value: DEBUG
            - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
              value: "1"
          resources:
            limits:
              memory: 128Gi
              cpu: "32"
              nvidia.com/gpu: "1"
              rdma/roce_gdr: "1"
            requests:
              memory: 128Gi
              cpu: "32"
              nvidia.com/gpu: "1"
              rdma/roce_gdr: "1"
          extraConfig:
            startupProbe:
              httpGet:
                path: /health
                port: 8200
              failureThreshold: 60
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
            livenessProbe:
              tcpSocket:
                port: 8200
              failureThreshold: 3
              periodSeconds: 5
            readinessProbe:
              httpGet:
                path: /health
                port: 8200
              failureThreshold: 3
              periodSeconds: 5
          volumeMounts: 
          - name: dshm
            mountPath: /dev/shm
        volumes: 
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      prefill:
        create: false

workload:
  harness: guidellm
  profile: something
  input_len: 10
  output_len: 50

upload_target:
  type: s3
  configuration:
    bucket: cloud-object-storage-cos-standard-ere
    endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud

