experiment:
  name: blis-training
  description: Training pipeline for BLIS scenario 5

stack:
  treatments:
    tensorParallelism:
      - 1
      - 2
      - 4

  model:
    helmValues:
      fullnameOverride: meta-llama-llama-3-1-8b-instruct
      multinode: false
      modelArtifacts:
        uri: pvc://model-pvc/models/meta-llama/Llama-3.1-8B-Instruct
        size: 300Gi
        authSecretName: "hf-secret"
        name: meta-llama/Llama-3.1-8B-Instruct
        labels:
          llm-d.ai/inferenceServing: "true"
          llm-d.ai/model: meta-llama-llama-3-1-8b-instruct

      routing:
        servicePort: 8000
        proxy:
          enabled: false
      decode:
        create: true
        replicas: 1
        acceleratorTypes:
            labelKey: nvidia.com/gpu.product
            labelValues:
              - NVIDIA-H100-80GB-HBM3
        parallelism:
          data: 1
          tensor: 1
        podAnnotations:
            k8s.v1.cni.cncf.io/networks: multi-nic-compute
        containers:
        - name: "vllm"
          env:
            - name: EXP_DATA_PATH
              value: /mnt/exp
          mountModelVolume: true
          image: "vllm/vllm-openai:v0.11.0"
          modelCommand: vllmServe
          args:
            - "--block-size"
            - "16"
            # - "--tensor-parallel-size"
            # - "1"
            # - "--max-model-len"
            # - "16000" 
            - "--max-num-batched-tokens"
            - "8192" 

          resources:
            limits:
              memory: 128Gi
              cpu: "32"
              nvidia.com/gpu: "1"
            requests:
              memory: 128Gi
              cpu: "32"
              nvidia.com/gpu: "1"
          extraConfig:
            startupProbe:
              httpGet:
                path: /health
                port: 8200
              failureThreshold: 60
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
            livenessProbe:
              tcpSocket:
                port: 8200
              failureThreshold: 3
              periodSeconds: 5
            readinessProbe:
              httpGet:
                path: /health
                port: 8200
              failureThreshold: 3
              periodSeconds: 5
          volumeMounts: 
          - name: data
            mountPath: /mnt/exp
        volumes: 
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      prefill:
        create: false
        replicas: 0

workload:
  harness: guidellm
  profile: something
  input_len: 10
  output_len: 50

upload_target:
  type: s3
  configuration:
    bucket: cloud-object-storage-cos-standard-ere
    endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud

